// <auto-generated />
using System;
using Amor_na_Pele_Squad09_Entrega02.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amor_na_Pele_Squad09_Entrega02.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220106012422_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Amor_na_Pele_Squad09_Entrega02.Models.CadastroContato", b =>
                {
                    b.Property<int>("ID_Contato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("emailContato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeContato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Contato");

                    b.ToTable("CadastroContato");
                });

            modelBuilder.Entity("Amor_na_Pele_Squad09_Entrega02.Models.CadastroEmpresa", b =>
                {
                    b.Property<int>("ID_Empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefoneEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricaoNegocio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeParaContatoEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Empresa");

                    b.ToTable("CadastroEmpresa");
                });

            modelBuilder.Entity("Amor_na_Pele_Squad09_Entrega02.Models.CadastroMulher", b =>
                {
                    b.Property<int>("ID_Mulher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailMulher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeMulher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTelefoneMulher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Mulher");

                    b.ToTable("CadastroMulher");
                });

            modelBuilder.Entity("Amor_na_Pele_Squad09_Entrega02.Models.CadastroNewsletter", b =>
                {
                    b.Property<int>("ID_Newsletter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("aceitaReceber")
                        .HasColumnType("bit");

                    b.Property<int>("emailNewsletter")
                        .HasColumnType("int");

                    b.Property<string>("nomeNewsletter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Newsletter");

                    b.ToTable("CadastroNewsletter");
                });
#pragma warning restore 612, 618
        }
    }
}
